# 04_04_pH_visualization.R
#
# Purpose:
#   Visualize soil pH differences between habitats.
#
# Input:
#   Data/Soil_analysis/
#     - metadata_patch_level.csv
#
#   Output/04_Soil_analysis/02_pH_processing/
#     - pH_test_result.csv
#
# Output:
#   Output/04_Soil_analysis/04_pH_visualization/
#     - soil_pH_plot.pdf
#
# Plot:
#   - Boxplots with individual observations
#   - Faceted by site
#   - BH-adjusted significance annotations
#
# R version:
#   R 4.5.3
#
# Packages:
#   tidyverse
#   here
#   rstatix
#   ggpubr

# ======================================================================
# 1. Setup
# ======================================================================
library(tidyverse)
library(here)
library(rstatix)
library(ggpubr)

# Input and output directories ------------------------------------------
input <- here("Data", "Soil_analysis")
processing_output <- here("Output", "04_Soil_analysis", "02_pH_processing")
output <- here("Output", "04_Soil_analysis", "04_pH_visualization")
dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Load data
# ======================================================================
# Soil pH data measured at the sampling-patch level.
metadata_patch <- read.csv(file.path(input, "metadata_patch_level.csv")) |>
  mutate(habitat = factor(habitat, levels = c("Solfatara field", "Forest edge")))

# Wilcoxon test results generated by 02_pH_processing.R.
test_pH <- read.csv(file.path(processing_output, "pH_test_result.csv"))

# ======================================================================
# 3. Prepare significance annotations
# ======================================================================
sig_pH <- metadata_patch |>
  group_by(site) |>
  summarise(y_pos = max(pH, na.rm = TRUE) * 1.05, .groups = "drop") |>
  left_join(test_pH |> select(site, group1, group2, p.adj.signif), by = "site")

# ======================================================================
# 4. Create pH boxplot
# ======================================================================
ph <- ggplot(metadata_patch, aes(x = habitat, y = pH, fill = habitat)) +
  geom_boxplot(
    width = 0.65,
    outlier.shape = NA,
    color = "black",
    linewidth = 0.3
  ) +
  geom_jitter(
    color = "grey50",
    width = 0.12,
    size = 1.6,
    alpha = 0.6,
    show.legend = FALSE
  ) +
  stat_pvalue_manual(
    data = sig_pH,
    label = "p.adj.signif",
    y.position = "y_pos",
    size = 6,
    tip.length = 0.01
  ) +
  facet_wrap(~ site, scales = "free_y") +
  scale_fill_manual(
    values = c(
      "Solfatara field" = "#D55E00",
      "Forest edge" = "#0072B2"
    )
  ) +
  labs(x = NULL, y = "Soil pH") +
  theme_bw(base_size = 15) +
  theme(
    panel.grid = element_blank(),
    strip.background = element_rect(fill = "white", color = "black"),
    strip.text = element_text(size = 20),
    axis.text = element_text(size = 20),
    axis.title.y = element_text(size = 20),
    legend.title = element_text(size = 17),
    legend.text = element_text(size = 17),
    legend.position = "bottom"
  )

ph

# ======================================================================
# 5. Save figure
# ======================================================================
ggsave(
  filename = file.path(output, "soil_pH_plot.pdf"),
  plot = ph,
  width = 8,
  height = 6,
  dpi = 300,
  bg = "white"
)