# 06_05_TableS_PERMANOVA.R
#
# Purpose:
#   Create supplementary Word tables from the PERMANOVA result files
#   generated by 06_01_PERMANOVA.R.
#
# Input:
#   Output/06_Community_analysis/01_PERMANOVA/<data_type>/
#     - <data_type>_<sample_type>_PERMANOVA_th3.csv
#
# Output:
#   Output/06_Community_analysis/05_Tables/PERMANOVA/
#     - <data_type>_<sample_type>_TableS_PERMANOVA.docx
#
# R version:
#   R 4.5.3
#
# Packages:
#   dplyr
#   flextable
#   officer
#   here

# ======================================================================
# 1. Setup
# ======================================================================
library(dplyr)
library(flextable)
library(officer)
library(here)

# Conditions to include ------------------------------------------------
conditions <- tidyr::expand_grid(
  data_type = c("Prokaryote", "Fungi"),
  sample_type = c("Root", "Root&Soil")
)

# Input and output directories -----------------------------------------
input <- here("Output", "06_Community_analysis", "01_PERMANOVA")
output <- here(
  "Output", "06_Community_analysis", "05_Tables", "PERMANOVA"
)
dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Helper functions
# ======================================================================
prepare_permanova_results <- function(results) {
  required_columns <- c(
    "Factors", "Df", "SumOfSqs", "R2", "F", "Pr(>F)"
  )
  missing_columns <- setdiff(required_columns, names(results))

  if (length(missing_columns) > 0) {
    stop(
      "Missing required column(s): ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  results |>
    transmute(
      Factors = recode(
        Factors,
        "habitat" = "Habitat",
        "host" = "Host",
        "sample_type" = "Sample type",
        "habitat:host" = "Habitat × Host",
        "habitat:sample_type" = "Habitat × Sample type"
      ),
      df = as.integer(Df),
      SS = as.numeric(SumOfSqs),
      R2 = as.numeric(R2),
      F_val = as.numeric(F),
      P_val = case_when(
        is.na(`Pr(>F)`) ~ "",
        `Pr(>F)` < 0.001 ~ "< 0.001",
        TRUE ~ sprintf("%.3f", `Pr(>F)`)
      )
    )
}

make_permanova_table <- function(results) {
  table_data <- prepare_permanova_results(results)

  flextable(table_data) |>
    set_header_labels(Factors = "Factor") |>
    compose(
      part = "header",
      j = "df",
      value = as_paragraph(as_i("df"))
    ) |>
    compose(
      part = "header",
      j = "SS",
      value = as_paragraph("SS")
    ) |>
    compose(
      part = "header",
      j = "R2",
      value = as_paragraph(as_i("R"), as_sup("2"))
    ) |>
    compose(
      part = "header",
      j = "F_val",
      value = as_paragraph(as_i("F"))
    ) |>
    compose(
      part = "header",
      j = "P_val",
      value = as_paragraph(as_i("P"))
    ) |>
    colformat_int(j = "df", na_str = "") |>
    colformat_double(
      j = c("SS", "R2", "F_val"),
      digits = 3,
      na_str = ""
    ) |>
    theme_booktabs() |>
    align(align = "center", part = "all") |>
    align(j = "Factors", align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    set_table_properties(layout = "autofit", width = 1)
}

make_caption <- function(data_type, sample_type) {
  community_label <- case_when(
    data_type == "Prokaryote" ~ "prokaryotic",
    data_type == "Fungi" ~ "fungal",
    TRUE ~ tolower(data_type)
  )

  sample_label <- case_when(
    sample_type == "Root" ~ "root",
    sample_type == "Root&Soil" ~ "root and soil",
    TRUE ~ tolower(sample_type)
  )

  factor_label <- case_when(
    sample_type == "Root" ~ "habitat, host plant, and their interaction",
    sample_type == "Root&Soil" ~
      "habitat, sample type, and their interaction",
    TRUE ~ "the explanatory factors"
  )

  paste0(
    "Table SX. Results of permutational multivariate analysis of variance ",
    "(PERMANOVA) testing the effects of ", factor_label, " on ",
    sample_label, " ", community_label,
    " community composition based on Sørensen dissimilarity."
  )
}

write_permanova_table <- function(data_type, sample_type, input, output) {
  input_file <- file.path(
    input,
    data_type,
    paste0(data_type, "_", sample_type, "_PERMANOVA_th3.csv")
  )

  if (!file.exists(input_file)) {
    stop("Input file not found: ", input_file, call. = FALSE)
  }

  # 06_01_PERMANOVA.R writes model terms as CSV row names.
  results <- read.csv(
    input_file,
    row.names = 1,
    check.names = FALSE,
    stringsAsFactors = FALSE
  ) |>
    tibble::rownames_to_column(var = "Factors")

  ft <- make_permanova_table(results)

  doc <- read_docx() |>
    body_add_par(
      make_caption(data_type, sample_type),
      style = "Normal"
    ) |>
    body_add_flextable(ft)

  output_file <- file.path(
    output,
    paste0(data_type, "_", sample_type, "_TableS_PERMANOVA.docx")
  )

  print(doc, target = output_file)
  message("Saved: ", output_file)

  invisible(output_file)
}

# ======================================================================
# 3. Create Word tables
# ======================================================================
output_files <- Map(
  write_permanova_table,
  data_type = conditions$data_type,
  sample_type = conditions$sample_type,
  MoreArgs = list(input = input, output = output)
)
