# 06_05_TableS_PERMANOVA.R
#
# Purpose:
#   Create supplementary Word tables from the PERMANOVA result files
#   generated by 06_01_PERMANOVA.R.
#
# R version:
#   R 4.5.3

# ======================================================================
# 1. Setup
# ======================================================================
library(dplyr)
library(flextable)
library(officer)
library(here)

conditions <- tidyr::expand_grid(
  data_type = c("Prokaryote", "Fungi"),
  sample_type = c("Root", "Root&Soil")
)

input <- here("Output", "06_Community_analysis", "01_PERMANOVA")
output <- here("Output", "06_Community_analysis", "05_Tables", "PERMANOVA")

dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Helper functions
# ======================================================================

format_p_value <- function(x) {
  case_when(
    is.na(x) ~ "",
    x < 0.001 ~ "< 0.001",
    TRUE ~ sprintf("%.3f", x)
  )
}

read_permanova_result <- function(file, test_label, factor_label, permutation_label) {
  if (!file.exists(file)) stop("Input file not found: ", file, call. = FALSE)
  
  results <- read.csv(file, row.names = 1, check.names = FALSE, stringsAsFactors = FALSE) |>
    tibble::rownames_to_column(var = "Factor")
  
  if (!"FDR" %in% names(results)) results$FDR <- NA_real_
  
  results |>
    transmute(
      Test = test_label,
      Permutation = permutation_label,
      Factor = case_when(
        Factor %in% c("habitat", "sample_type") ~ factor_label,
        Factor == "Residual" ~ "Residual",
        Factor == "Total" ~ "Total",
        TRUE ~ Factor
      ),
      df = as.integer(Df),
      SS = as.numeric(SumOfSqs),
      R2 = as.numeric(R2),
      F_val = as.numeric(F),
      P_val = as.numeric(`Pr(>F)`),
      FDR = as.numeric(FDR)
    )
}

prepare_root_results <- function(file) {
  if (!file.exists(file)) stop("Input file not found: ", file, call. = FALSE)
  
  read.csv(file, row.names = 1, check.names = FALSE, stringsAsFactors = FALSE) |>
    tibble::rownames_to_column(var = "Factor") |>
    transmute(
      Test = "Overall model",
      Permutation = "Within site",
      Factor = recode(
        Factor,
        "habitat" = "Habitat",
        "host" = "Host plant",
        "habitat:host" = "Habitat × Host",
        "Residual" = "Residual",
        "Total" = "Total"
      ),
      df = as.integer(Df),
      SS = as.numeric(SumOfSqs),
      R2 = as.numeric(R2),
      F_val = as.numeric(F),
      P_val = as.numeric(`Pr(>F)`),
      FDR = NA_real_
    )
}

make_permanova_table <- function(results) {
  include_fdr <- any(!is.na(results$FDR))
  
  table_data <- results |>
    mutate(
      P_val = format_p_value(P_val),
      FDR = format_p_value(FDR)
    )
  
  if (!include_fdr) table_data <- select(table_data, -FDR)
  
  flextable(table_data) |>
    set_header_labels(
      Test = "Test", Permutation = "Permutation restriction",
      Factor = "Factor", SS = "SS", FDR = "FDR"
    ) |>
    compose(part = "header", j = "df", value = as_paragraph(as_i("df"))) |>
    compose(part = "header", j = "R2", value = as_paragraph(as_i("R"), as_sup("2"))) |>
    compose(part = "header", j = "F_val", value = as_paragraph(as_i("F"))) |>
    compose(part = "header", j = "P_val", value = as_paragraph(as_i("P"))) |>
    colformat_int(j = "df", na_str = "") |>
    colformat_double(j = c("SS", "R2", "F_val"), digits = 3, na_str = "") |>
    theme_booktabs() |>
    merge_v(j = c("Test", "Permutation")) |>
    valign(j = c("Test", "Permutation"), valign = "top", part = "body") |>
    align(align = "center", part = "all") |>
    align(j = c("Test", "Permutation", "Factor"), align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    set_table_properties(layout = "autofit", width = 1)
}

make_caption <- function(data_type, sample_type) {
  community_label <- case_when(
    data_type == "Prokaryote" ~ "prokaryotic",
    data_type == "Fungi" ~ "fungal",
    TRUE ~ tolower(data_type)
  )
  
  if (sample_type == "Root") {
    paste0(
      "Table SX. PERMANOVA testing habitat, host plant, and their ",
      "interaction for root ", community_label, " communities based on Sørensen dissimilarity."
    )
  } else {
    paste0(
      "Table SX. PERMANOVA for the root–soil subset of ", community_label,
      " communities. Habitat effects were tested separately within root and soil samples, ",
      "and sample-type effects were tested separately within each habitat."
    )
  }
}

get_result_file <- function(input, data_type, sample_type, suffix = NULL) {
  filename <- if (is.null(suffix)) {
    paste0(data_type, "_", sample_type, "_PERMANOVA_th3.csv")
  } else {
    paste0(data_type, "_", sample_type, "_PERMANOVA_", suffix, "_th3.csv")
  }
  file.path(input, data_type, filename)
}

# ======================================================================
# 3. Create Word tables
# ======================================================================

write_permanova_table <- function(data_type, sample_type, input, output) {
  if (sample_type == "Root") {
    results <- prepare_root_results(get_result_file(input, data_type, sample_type))
  } else if (sample_type == "Root&Soil") {
    results <- bind_rows(
      read_permanova_result(
        get_result_file(input, data_type, sample_type, "habitat_root"),
        test_label = "Habitat within root subset", factor_label = "Habitat",
        permutation_label = "Within site"
      ),
      read_permanova_result(
        get_result_file(input, data_type, sample_type, "habitat_soil"),
        test_label = "Habitat within soil", factor_label = "Habitat",
        permutation_label = "Within site"
      ),
      read_permanova_result(
        get_result_file(input, data_type, sample_type, "Solfatara_field"),
        test_label = "Sample type within Solfatara field", factor_label = "Sample type",
        permutation_label = "Within SID"
      ),
      read_permanova_result(
        get_result_file(input, data_type, sample_type, "sample_type_Forest_edge"),
        test_label = "Sample type within forest edge", factor_label = "Sample type",
        permutation_label = "Within SID"
      )
    )
  } else {
    stop("Unsupported sample_type: ", sample_type, call. = FALSE)
  }
  
  doc <- read_docx() |>
    body_add_par(make_caption(data_type, sample_type), style = "Normal") |>
    body_add_flextable(make_permanova_table(results))
  
  output_file <- file.path(output, paste0(data_type, "_", sample_type,
                                          "_TableS_PERMANOVA.docx"))
  
  print(doc, target = output_file)
  message("Saved: ", output_file)
  invisible(output_file)
}

output_files <- Map(
  write_permanova_table,
  data_type = conditions$data_type,
  sample_type = conditions$sample_type,
  MoreArgs = list(input = input, output = output)
)