# 06_06_TableS_PERMDISP.R
#
# Purpose:
#   Create supplementary Word tables summarizing PERMDISP results
#   generated by 06_03_PERMDISP.R.
#
# Analysis design:
#   Root:
#     - Habitat: permutations restricted within site
#     - Host: permutations restricted within site
#     - Pairwise host comparisons: permutations restricted within site
#
#   Root&Soil:
#     - Habitat within Root subset: permutations restricted within site
#     - Habitat within Soil: permutations restricted within site
#     - Root vs Soil within Solfatara field: permutations restricted within SID
#     - Root vs Soil within Forest edge: permutations restricted within SID
#
#   Bias adjustment:
#     - bias.adjust = TRUE was applied to all PERMDISP analyses in 06_03_PERMDISP.R.
#
#   Multiple testing:
#     - BH FDR correction is applied separately to:
#         (1) Root vs Soil tests within the two habitats
#         (2) Habitat tests within Root subset and Soil
#         (3) Pairwise host comparisons
#
# Input: Output/06_Community_analysis/03_PERMDISP/
# Output: Output/06_Community_analysis/06_Tables/
#
# R version: R 4.5.3
# Packages: dplyr, tidyr, flextable, officer, here

# ======================================================================
# 1. Setup
# ======================================================================

library(dplyr)
library(tidyr)
library(flextable)
library(officer)
library(here)

conditions <- tidyr::expand_grid(
  data_type = c("Prokaryote", "Fungi"),
  sample_type = c("Root", "Root&Soil")
)

input <- here("Output", "06_Community_analysis", "03_PERMDISP")
output <- here("Output", "06_Community_analysis", "PERMDISP_Tables")

dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Helper functions
# ======================================================================

format_p_value <- function(x) {
  case_when(
    is.na(x) ~ "",
    x < 0.001 ~ "< 0.001",
    TRUE ~ sprintf("%.3f", x)
  )
}

get_result_file <- function(input, data_type, sample_type, suffix) {
  file.path(input, data_type, sample_type, paste0(data_type, "_", sample_type, "_PERMDISP_", suffix, "_th3.csv"))
}

read_permdisp_result <- function(file, test_label, factor_label, permutation_label) {
  if (!file.exists(file)) stop("Input file not found: ", file, call. = FALSE)
  
  result <- read.csv(file, row.names = 1, check.names = FALSE, stringsAsFactors = FALSE) |>
    tibble::rownames_to_column(var = "Factor")
  
  if (!"FDR" %in% names(result)) result$FDR <- NA_real_
  
  result |>
    transmute(
      Test = test_label,
      Permutation = permutation_label,
      Factor = case_when(
        Factor == "Groups" ~ factor_label,
        Factor == "Residuals" ~ "Residual",
        TRUE ~ Factor
      ),
      df = as.integer(Df),
      SS = as.numeric(`Sum Sq`),
      MS = as.numeric(`Mean Sq`),
      F_value = as.numeric(F),
      P_value = as.numeric(`Pr(>F)`),
      FDR = as.numeric(FDR)
    )
}

read_pairwise_host_result <- function(file) {
  if (!file.exists(file)) stop("Input file not found: ", file, call. = FALSE)
  
  result <- read.csv(file, check.names = FALSE, stringsAsFactors = FALSE)
  
  required_columns <- c("comparison", "FDR")
  missing_columns <- setdiff(required_columns, names(result))
  
  if (length(missing_columns) > 0) {
    stop("Missing required column(s) in ", basename(file), ": ", 
         paste(missing_columns, collapse = ", "), call. = FALSE)
  }
  
  result |>
    transmute(
      Comparison = comparison,
      Permutation = "Within site",
      P_value = as.numeric(p_perm),
      FDR = as.numeric(FDR)
    )
}

# ======================================================================
# 3. Flextable: Omnibus tests
# ======================================================================

make_permdisp_table <- function(results) {
  include_fdr <- any(!is.na(results$FDR))
  
  table_data <- results |>
    mutate(
      P_value = format_p_value(P_value),
      FDR = format_p_value(FDR)
    )
  
  if (include_fdr) {
    table_data <- select(table_data, -P_value)
  } else {
    table_data <- select(table_data, -FDR)
  }
  
  ft <- flextable(table_data)
  if (!include_fdr) {
    ft <- compose(ft, part = "header", j = "P_value", value = as_paragraph(as_i("P")))
  }
  
  ft |>
    set_header_labels(
      Test = "Test", Permutation = "Permutation restriction",
      Factor = "Factor", SS = "SS", MS = "MS", FDR = "FDR"
    ) |>
    compose(part = "header", j = "df", value = as_paragraph(as_i("df"))) |>
    compose(part = "header", j = "F_value", value = as_paragraph(as_i("F"))) |>
    colformat_int(j = "df", na_str = "") |>
    colformat_double(j = c("SS", "MS", "F_value"), digits = 3, na_str = "") |>
    theme_booktabs() |>
    merge_v(j = c("Test", "Permutation")) |>
    valign(j = c("Test", "Permutation"), valign = "top", part = "body") |>
    align(align = "center", part = "all") |>
    align(j = c("Test", "Permutation", "Factor"), align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    width(j = "Test", width = 1.25) |>
    width(j = "Permutation", width = 1.15) |>
    width(j = "Factor", width = 1.00) |>
    width(j = "df", width = 0.40) |>
    width(j = c("SS", "MS", "F_value"), width = 0.60) |>
    width(j = if (include_fdr) "FDR" else "P_value", width = 0.70) |>
    set_table_properties(layout = "fixed")
}

# ======================================================================
# 4. Flextable: Pairwise host tests
# ======================================================================
make_pairwise_table <- function(results) {
  table_data <- results |>
    select(-any_of("P_value")) |>
    mutate(
      FDR = format_p_value(FDR)
    )
  
  flextable(table_data) |>
    set_header_labels(
      Comparison = "Host comparison",
      Permutation = "Permutation restriction",
      FDR = "FDR"
    ) |>
    theme_booktabs() |>
    align(align = "center", part = "all") |>
    align(j = c("Comparison", "Permutation"), align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    width(j = "Comparison", width = 4.45) |>
    width(j = "Permutation", width = 1.15) |>
    width(j = "FDR", width = 0.70) |>
    set_table_properties(layout = "fixed")
}
# ======================================================================
# 5. Captions
# ======================================================================

make_caption <- function(data_type, sample_type) {
  community_label <- case_when(
    data_type == "Prokaryote" ~ "prokaryotic",
    data_type == "Fungi" ~ "fungal",
    TRUE ~ tolower(data_type)
  )
  
  if (sample_type == "Root") {
    paste0(
      "PERMDISP tests of multivariate dispersion among habitats and host plants for root ",
      community_label, " communities based on Sørensen dissimilarity. ",
      "Permutations were restricted within sites. ",
      "Bias-adjusted distances to group spatial medians were used."
    )
  } else {
    paste0(
      "PERMDISP tests for the root–soil subset of ", community_label,
      " communities based on Sørensen dissimilarity. ",
      "Habitat effects were tested separately within the root subset and soil samples using ",
      "permutations restricted within sites, whereas root–soil differences were tested separately ",
      "within each habitat using permutations restricted within sampling positions (SID). ",
      "Bias-adjusted distances to group spatial medians were used."
    )
  }
}

# ======================================================================
# 6. Create Root tables
# ======================================================================

create_root_table <- function(data_type, input, output) {
  sample_type <- "Root"
  
  habitat <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "habitat"),
    test_label = "Habitat", factor_label = "Habitat", permutation_label = "Within site"
  )
  
  host <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "host"),
    test_label = "Host plant", factor_label = "Host plant", permutation_label = "Within site"
  )
  
  omnibus <- bind_rows(habitat, host)
  
  pairwise_host <- read_pairwise_host_result(
    get_result_file(input, data_type, sample_type, "host_pairwise")
  )
  
  doc <- read_docx() |>
    body_add_par(make_caption(data_type, sample_type), style = "Normal") |>
    body_add_flextable(make_permdisp_table(omnibus)) |>
    body_add_par("", style = "Normal") |>
    body_add_par("Pairwise comparisons among host plants", style = "Normal") |>
    body_add_flextable(make_pairwise_table(pairwise_host))
  
  output_file <- file.path(output, paste0(data_type, "_Root_TableS_PERMDISP.docx"))
  
  print(doc, target = output_file)
  message("Saved: ", output_file)
  invisible(output_file)
}

# ======================================================================
# 7. Create Root&Soil tables
# ======================================================================

create_root_soil_table <- function(data_type, input, output) {
  sample_type <- "Root&Soil"
  
  habitat_root <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "habitat_root"),
    test_label = "Habitat within root subset", factor_label = "Habitat", permutation_label = "Within site"
  )
  
  habitat_soil <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "habitat_soil"),
    test_label = "Habitat within soil", factor_label = "Habitat", permutation_label = "Within site"
  )
  
  sample_type_sf <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "sample_type_Solfatara_field"),
    test_label = "Sample type within solfatara field", factor_label = "Sample type", 
    permutation_label = "Within sampling point"
  )
  
  sample_type_fe <- read_permdisp_result(
    get_result_file(input, data_type, sample_type, "sample_type_Forest_edge"),
    test_label = "Sample type within forest edge", factor_label = "Sample type", 
    permutation_label = "Within sampling point"
  )
  
  results <- bind_rows(habitat_root, habitat_soil, sample_type_sf, sample_type_fe)
  
  doc <- read_docx() |>
    body_add_par(make_caption(data_type, sample_type), style = "Normal") |>
    body_add_flextable(make_permdisp_table(results))
  
  output_file <- file.path(output, paste0(data_type, "_Root&Soil_TableS_PERMDISP.docx"))
  
  print(doc, target = output_file)
  message("Saved: ", output_file)
  invisible(output_file)
}

# ======================================================================
# 8. Generate all tables
# ======================================================================

for (data_type_i in c("Prokaryote", "Fungi")) {
  create_root_table(data_type = data_type_i, input = input, output = output)
  create_root_soil_table(data_type = data_type_i, input = input, output = output)
}