# 06_06_TableS_PERMDISP.R
#
# Purpose:
#   Create supplementary Word tables from the PERMDISP result files
#   generated by 06_03_PERMDISP.R.
#
# Input:
#   Output/03_Community_analysis/03_PERMDISP/<data_type>/<sample_type>/
#     - PERMDISP result CSV files generated by 06_03_PERMDISP.R
#
# Output:
#   Output/03_Community_analysis/06_Tables/PERMDISP/
#     - <data_type>_<sample_type>_TableS_PERMDISP.docx
#
# R version:
#   R 4.5.3
#
# Packages:
#   dplyr
#   flextable
#   officer
#   here

# ======================================================================
# 1. Setup
# ======================================================================
library(dplyr)
library(flextable)
library(officer)
library(here)

# Conditions to include ------------------------------------------------
conditions <- tidyr::expand_grid(
  data_type = c("Prokaryote", "Fungi"),
  sample_type = c("Root", "Root&Soil")
)

# Input and output directories -----------------------------------------
input <- here("Output", "03_Community_analysis", "03_PERMDISP")
output <- here(
  "Output", "03_Community_analysis", "06_Tables", "PERMDISP"
)
dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Helper functions
# ======================================================================
format_p_value <- function(x) {
  case_when(
    is.na(x) ~ "",
    x < 0.001 ~ "< 0.001",
    TRUE ~ sprintf("%.3f", x)
  )
}

read_permdisp_result <- function(file, test_label, group_label) {
  if (!file.exists(file)) {
    stop("Input file not found: ", file, call. = FALSE)
  }

  results <- read.csv(
    file,
    row.names = 1,
    check.names = FALSE,
    stringsAsFactors = FALSE
  ) |>
    tibble::rownames_to_column(var = "Factor")

  required_columns <- c(
    "Factor", "Df", "Sum Sq", "Mean Sq", "F", "Pr(>F)"
  )
  missing_columns <- setdiff(required_columns, names(results))

  if (length(missing_columns) > 0) {
    stop(
      "Missing required column(s) in ", basename(file), ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  if (!"FDR" %in% names(results)) {
    results$FDR <- NA_real_
  }

  results |>
    transmute(
      Test = test_label,
      Factor = recode(
        Factor,
        "Groups" = group_label,
        "Residuals" = "Residual"
      ),
      df = as.integer(Df),
      SS = as.numeric(`Sum Sq`),
      MS = as.numeric(`Mean Sq`),
      F_val = as.numeric(F),
      P_val = as.numeric(`Pr(>F)`),
      FDR = as.numeric(FDR)
    )
}

make_permdisp_table <- function(results) {
  include_fdr <- any(!is.na(results$FDR))

  table_data <- results |>
    mutate(
      P_val = format_p_value(P_val),
      FDR = format_p_value(FDR)
    )

  if (!include_fdr) {
    table_data <- select(table_data, -FDR)
  }

  ft <- flextable(table_data) |>
    set_header_labels(
      Test = "Test",
      Factor = "Factor",
      SS = "SS",
      MS = "MS",
      FDR = "FDR"
    ) |>
    compose(
      part = "header",
      j = "df",
      value = as_paragraph(as_i("df"))
    ) |>
    compose(
      part = "header",
      j = "F_val",
      value = as_paragraph(as_i("F"))
    ) |>
    compose(
      part = "header",
      j = "P_val",
      value = as_paragraph(as_i("P"))
    ) |>
    colformat_int(j = "df", na_str = "") |>
    colformat_double(
      j = c("SS", "MS", "F_val"),
      digits = 3,
      na_str = ""
    ) |>
    theme_booktabs() |>
    merge_v(j = "Test") |>
    valign(j = "Test", valign = "top", part = "body") |>
    align(align = "center", part = "all") |>
    align(j = c("Test", "Factor"), align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    set_table_properties(layout = "autofit", width = 1)

  ft
}

read_pairwise_host_result <- function(file) {
  if (!file.exists(file)) {
    stop("Input file not found: ", file, call. = FALSE)
  }

  results <- read.csv(
    file,
    check.names = FALSE,
    stringsAsFactors = FALSE
  )

  required_columns <- c("comparison", "p_perm", "FDR")
  missing_columns <- setdiff(required_columns, names(results))

  if (length(missing_columns) > 0) {
    stop(
      "Missing required column(s) in ", basename(file), ": ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  results |>
    transmute(
      Comparison = sub("-", " – ", comparison, fixed = TRUE),
      P_val = format_p_value(p_perm),
      FDR = format_p_value(FDR)
    )
}

make_pairwise_table <- function(results) {
  flextable(results) |>
    set_header_labels(Comparison = "Host comparison", FDR = "FDR") |>
    compose(
      part = "header",
      j = "P_val",
      value = as_paragraph(as_i("P"))
    ) |>
    theme_booktabs() |>
    align(align = "center", part = "all") |>
    align(j = "Comparison", align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    set_table_properties(layout = "autofit", width = 1)
}

make_caption <- function(data_type, sample_type) {
  community_label <- case_when(
    data_type == "Prokaryote" ~ "prokaryotic",
    data_type == "Fungi" ~ "fungal",
    TRUE ~ tolower(data_type)
  )

  sample_label <- case_when(
    sample_type == "Root" ~ "root",
    sample_type == "Root&Soil" ~ "root and soil",
    TRUE ~ tolower(sample_type)
  )

  paste0(
    "Table SX. Results of permutational analysis of multivariate ",
    "dispersions (PERMDISP) for ", sample_label, " ", community_label,
    " communities based on Sørensen dissimilarity."
  )
}

get_result_file <- function(input_dir, data_type, sample_type, suffix) {
  file.path(
    input_dir,
    data_type,
    sample_type,
    paste0(
      data_type, "_", sample_type, "_PERMDISP_", suffix, "_th3.csv"
    )
  )
}

# ======================================================================
# 3. Create a Word table for each dataset
# ======================================================================
write_permdisp_table <- function(data_type, sample_type, input, output) {
  if (sample_type == "Root") {
    omnibus_results <- bind_rows(
      read_permdisp_result(
        get_result_file(input, data_type, sample_type, "habitat"),
        test_label = "Habitat",
        group_label = "Habitat"
      ),
      read_permdisp_result(
        get_result_file(input, data_type, sample_type, "host"),
        test_label = "Host plant",
        group_label = "Host plant"
      )
    )

    pairwise_results <- read_pairwise_host_result(
      get_result_file(input, data_type, sample_type, "host_pairwise")
    )
  } else if (sample_type == "Root&Soil") {
    omnibus_results <- bind_rows(
      read_permdisp_result(
        get_result_file(input, data_type, sample_type, "habitat_root"),
        test_label = "Habitat within roots",
        group_label = "Habitat"
      ),
      read_permdisp_result(
        get_result_file(input, data_type, sample_type, "habitat_soil"),
        test_label = "Habitat within soil",
        group_label = "Habitat"
      ),
      read_permdisp_result(
        get_result_file(input, data_type, sample_type, "Solfatara_field"),
        test_label = "Sample type within Solfatara field",
        group_label = "Sample type"
      ),
      read_permdisp_result(
        get_result_file(
          input, data_type, sample_type, "sample_type_Forest_edge"
        ),
        test_label = "Sample type within forest edge",
        group_label = "Sample type"
      )
    )
  } else {
    stop("Unsupported sample_type: ", sample_type, call. = FALSE)
  }

  doc <- read_docx() |>
    body_add_par(
      make_caption(data_type, sample_type),
      style = "Normal"
    )

  if (sample_type == "Root") {
    doc <- doc |>
      body_add_par("(a) Overall tests", style = "Normal") |>
      body_add_flextable(make_permdisp_table(omnibus_results)) |>
      body_add_par("(b) Pairwise host comparisons", style = "Normal") |>
      body_add_flextable(make_pairwise_table(pairwise_results))
  } else {
    doc <- doc |>
      body_add_flextable(make_permdisp_table(omnibus_results))
  }

  output_file <- file.path(
    output,
    paste0(data_type, "_", sample_type, "_TableS_PERMDISP.docx")
  )

  print(doc, target = output_file)
  message("Saved: ", output_file)

  invisible(output_file)
}

output_files <- Map(
  write_permdisp_table,
  data_type = conditions$data_type,
  sample_type = conditions$sample_type,
  MoreArgs = list(input = input, output = output)
)
