# 06_07_TableS_Varpart.R
#
# Purpose:
#   Create supplementary Word tables from the variation-partitioning
#   summary files generated by 06_02_Variation_partitioning.R.
#
# Input:
#   Output/03_Community_analysis/02_Variation_partitioning/<data_type>/
#     - <data_type>_<sample_type>_Variation_partitioning_summary_table_th3.csv
#
# Output:
#   Output/03_Community_analysis/07_Tables/Variation_partitioning/
#     - <data_type>_<sample_type>_TableS_Varpart.docx
#
# R version:
#   R 4.5.3
#
# Packages:
#   dplyr
#   flextable
#   officer
#   here

# ======================================================================
# 1. Setup
# ======================================================================
library(dplyr)
library(flextable)
library(officer)
library(here)

# Conditions to include ------------------------------------------------
conditions <- tidyr::expand_grid(
  data_type = c("Prokaryote", "Fungi"),
  sample_type = c("Root", "Root&Soil")
)

# Input and output directories -----------------------------------------
input <- here(
  "Output", "06_Community_analysis", "02_Variation_partitioning"
)
output <- here(
  "Output", "06_Community_analysis", "Varpart_Tables")
dir.create(output, showWarnings = FALSE, recursive = TRUE)

# ======================================================================
# 2. Helper functions
# ======================================================================
make_varpart_table <- function(results) {
  required_columns <- c("Partition", "Adj_R2", "df")
  missing_columns <- setdiff(required_columns, names(results))

  if (length(missing_columns) > 0) {
    stop(
      "Missing required column(s): ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  table_data <- results |>
    transmute(
      Partition,
      Adj_R2 = as.numeric(Adj_R2),
      df = as.integer(df)
    )

  flextable(table_data) |>
    set_header_labels(Partition = "Partition") |>
    compose(
      part = "header",
      j = "Adj_R2",
      value = as_paragraph("Adjusted ", as_i("R"), as_sup("2"))
    ) |>
    compose(
      part = "header",
      j = "df",
      value = as_paragraph(as_i("df"))
    ) |>
    colformat_double(j = "Adj_R2", digits = 3, na_str = "") |>
    colformat_int(j = "df", na_str = "") |>
    theme_booktabs() |>
    align(align = "center", part = "all") |>
    align(j = "Partition", align = "left", part = "all") |>
    bold(part = "header") |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    autofit() |>
    set_table_properties(layout = "autofit", width = 1)
}

make_caption <- function(data_type, sample_type) {
  community_label <- dplyr::case_when(
    data_type == "Prokaryote" ~ "prokaryotic",
    data_type == "Fungi" ~ "fungal",
    TRUE ~ tolower(data_type)
  )

  sample_label <- dplyr::case_when(
    sample_type == "Root" ~ "root",
    sample_type == "Root&Soil" ~ "root and soil",
    TRUE ~ tolower(sample_type)
  )

  paste0(
    "Table SX. Results of variation partitioning analysis of ",
    sample_label, " ", community_label,
    " community based on Sørensen dissimilarity."
  )
}

write_varpart_table <- function(data_type, sample_type, input, output) {
  input_file <- file.path(
    input,
    data_type,
    paste0(
      data_type, "_", sample_type,
      "_Variation_partitioning_summary_table_th3.csv"
    )
  )

  if (!file.exists(input_file)) {
    stop("Input file not found: ", input_file, call. = FALSE)
  }

  results <- read.csv(
    input_file,
    check.names = FALSE,
    stringsAsFactors = FALSE,
    na.strings = c("", "NA")
  )

  ft <- make_varpart_table(results)

  doc <- read_docx() |>
    body_add_par(
      make_caption(data_type, sample_type),
      style = "Normal"
    ) |>
    body_add_flextable(ft)

  output_file <- file.path(
    output,
    paste0(data_type, "_", sample_type, "_TableS_Varpart.docx")
  )

  print(doc, target = output_file)
  message("Saved: ", output_file)

  invisible(output_file)
}

# ======================================================================
# 3. Create Word tables
# ======================================================================
output_files <- Map(
  write_varpart_table,
  data_type = conditions$data_type,
  sample_type = conditions$sample_type,
  MoreArgs = list(input = input, output = output)
)
